-- liquibase formatted sql

-- changeset araf:1
CREATE TABLE "roles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, CONSTRAINT "roles_pkey" PRIMARY KEY ("id"));

-- changeset araf:2
CREATE TABLE "permissions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, CONSTRAINT "permissions_pkey" PRIMARY KEY ("id"));

-- changeset araf:3
CREATE TABLE "users" ("id" UUID NOT NULL, "user_name" VARCHAR NOT NULL, "email" VARCHAR NOT NULL, "password" VARCHAR NOT NULL, "password_salt" VARCHAR NOT NULL, "role_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset araf:4
CREATE TABLE "departments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_by" UUID NOT NULL, "last_updated_at" TIMESTAMP WITHOUT TIME ZONE, "last_updated_by" UUID, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "departments_pkey" PRIMARY KEY ("id"));

-- changeset araf:5
CREATE TABLE "programs" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_by" UUID NOT NULL, "last_updated_at" TIMESTAMP WITHOUT TIME ZONE, "last_updated_by" UUID, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "programs_pkey" PRIMARY KEY ("id"));

-- changeset araf:6
CREATE TABLE "sessions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "years" VARCHAR NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_by" UUID NOT NULL, "last_updated_at" TIMESTAMP WITHOUT TIME ZONE, "last_updated_by" UUID, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "sessions_pkey" PRIMARY KEY ("id"));

-- changeset araf:7
CREATE TABLE "user_sessions" ("id" UUID NOT NULL, "user_id" UUID, "ip_address" VARCHAR NOT NULL, "os" VARCHAR NOT NULL, "device" VARCHAR NOT NULL, "browser" VARCHAR NOT NULL, "token" VARCHAR NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "user_sessions_pkey" PRIMARY KEY ("id"));

-- changeset araf:8
CREATE TABLE "hall_of_fames" ("id" UUID NOT NULL, "title" VARCHAR NOT NULL, "description" VARCHAR, "image_id" UUID, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_by" UUID NOT NULL, "last_updated_at" TIMESTAMP WITHOUT TIME ZONE, "last_updated_by" UUID, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "hall_of_fames_pkey" PRIMARY KEY ("id"));

-- changeset araf:9
CREATE TABLE "events" ("id" UUID NOT NULL, "title" VARCHAR NOT NULL, "description" VARCHAR, "banner_id" UUID, "start_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "end_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "venue" VARCHAR NOT NULL, "event_link" VARCHAR, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_by" UUID NOT NULL, "last_updated_at" TIMESTAMP WITHOUT TIME ZONE, "last_updated_by" UUID, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "events_pkey" PRIMARY KEY ("id"));

-- changeset araf:10
CREATE TABLE "executive_commitees" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "label" VARCHAR NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_by" UUID NOT NULL, "last_updated_at" TIMESTAMP WITHOUT TIME ZONE, "last_updated_by" UUID, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "executive_commitees_pkey" PRIMARY KEY ("id"));

-- changeset araf:11
CREATE TABLE "ec_members" ("id" UUID NOT NULL, "user_id" UUID, "post" VARCHAR NOT NULL, "first_name" VARCHAR, "last_name" VARCHAR, "note" VARCHAR, "image_id" UUID, "committee_id" INTEGER NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "ec_members_pkey" PRIMARY KEY ("id"));

-- changeset araf:12
ALTER TABLE "roles" ADD CONSTRAINT "roles_name_key" UNIQUE ("name");

-- changeset araf:13
ALTER TABLE "permissions" ADD CONSTRAINT "permissions_name_key" UNIQUE ("name");

-- changeset araf:14
ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");

-- changeset araf:15
ALTER TABLE "users" ADD CONSTRAINT "users_user_name_key" UNIQUE ("user_name");

-- changeset araf:16
ALTER TABLE "departments" ADD CONSTRAINT "departments_name_key" UNIQUE ("name");

-- changeset araf:17
ALTER TABLE "programs" ADD CONSTRAINT "programs_name_key" UNIQUE ("name");

-- changeset araf:18
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_years_key" UNIQUE ("years");

-- changeset araf:19
CREATE TABLE "images" ("id" UUID NOT NULL, "url" VARCHAR, CONSTRAINT "images_pkey" PRIMARY KEY ("id"));

-- changeset araf:20
CREATE TABLE "people_in_hall_of_fame" ("user_id" UUID NOT NULL, "hall_of_fame_id" UUID NOT NULL, CONSTRAINT "people_in_hall_of_fame_pkey" PRIMARY KEY ("user_id", "hall_of_fame_id"));

-- changeset araf:21
CREATE TABLE "profiles" ("user_id" UUID NOT NULL, "first_name" VARCHAR, "last_name" VARCHAR, "reg_no" VARCHAR, "department_id" INTEGER, "program_id" INTEGER, "session_id" INTEGER, "codeforces_handle" VARCHAR, "atcoder_handle" VARCHAR, "vjudge_handle" VARCHAR, "discord_handle" VARCHAR, "github_handle" VARCHAR, "google_account" VARCHAR, "image_id" UUID, "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "is_deleted" BOOLEAN NOT NULL, CONSTRAINT "profiles_pkey" PRIMARY KEY ("user_id"));

-- changeset araf:22
CREATE TABLE "role_permissions" ("role_id" INTEGER NOT NULL, "permission_id" INTEGER NOT NULL, CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role_id", "permission_id"));

-- changeset araf:23
ALTER TABLE "departments" ADD CONSTRAINT "departments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:24
ALTER TABLE "departments" ADD CONSTRAINT "departments_last_updated_by_fkey" FOREIGN KEY ("last_updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:25
ALTER TABLE "ec_members" ADD CONSTRAINT "ec_members_committee_id_fkey" FOREIGN KEY ("committee_id") REFERENCES "executive_commitees" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:26
ALTER TABLE "ec_members" ADD CONSTRAINT "ec_members_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "images" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:27
ALTER TABLE "ec_members" ADD CONSTRAINT "ec_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:28
ALTER TABLE "events" ADD CONSTRAINT "events_banner_id_fkey" FOREIGN KEY ("banner_id") REFERENCES "images" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:29
ALTER TABLE "events" ADD CONSTRAINT "events_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:30
ALTER TABLE "events" ADD CONSTRAINT "events_last_updated_by_fkey" FOREIGN KEY ("last_updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:31
ALTER TABLE "executive_commitees" ADD CONSTRAINT "executive_commitees_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:32
ALTER TABLE "executive_commitees" ADD CONSTRAINT "executive_commitees_last_updated_by_fkey" FOREIGN KEY ("last_updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:33
ALTER TABLE "hall_of_fames" ADD CONSTRAINT "hall_of_fames_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:34
ALTER TABLE "hall_of_fames" ADD CONSTRAINT "hall_of_fames_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "images" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:35
ALTER TABLE "hall_of_fames" ADD CONSTRAINT "hall_of_fames_last_updated_by_fkey" FOREIGN KEY ("last_updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:36
ALTER TABLE "people_in_hall_of_fame" ADD CONSTRAINT "people_in_hall_of_fame_hall_of_fame_id_fkey" FOREIGN KEY ("hall_of_fame_id") REFERENCES "hall_of_fames" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:37
ALTER TABLE "people_in_hall_of_fame" ADD CONSTRAINT "people_in_hall_of_fame_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:38
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:39
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "images" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:40
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:41
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:42
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:43
ALTER TABLE "programs" ADD CONSTRAINT "programs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:44
ALTER TABLE "programs" ADD CONSTRAINT "programs_last_updated_by_fkey" FOREIGN KEY ("last_updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:45
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:46
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:47
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:48
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_last_updated_by_fkey" FOREIGN KEY ("last_updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:49
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset araf:50
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

